# Generated by Django 4.2.7 on 2023-11-09 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_male', models.BooleanField(default=False, help_text='Designates that the classmate has male gender.', verbose_name='Male')),
                ('is_female', models.BooleanField(default=False, help_text='Designates that the classmate has female gender.', verbose_name='Female')),
                ('is_other', models.BooleanField(default=False, help_text='Designates that the classmate has other gender.', verbose_name='Other')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Designates the first name of the classmate.', max_length=65, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Designates the last name of the classmate.', max_length=65, null=True, verbose_name='Last Name')),
                ('age', models.IntegerField(help_text='Designates the age of the classmate.', null=True, verbose_name='Age')),
                ('email', models.EmailField(help_text='Designates the email of the classmate.', max_length=65, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Designates the phone number of the classmate.', max_length=10, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, help_text='Designates the address of the classmate.', max_length=65, null=True, verbose_name='Address')),
                ('profile_photo', models.ImageField(blank=True, help_text='Designates the profile photo of the classmate.', null=True, upload_to='profiles', verbose_name='Profile Photo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Designates the date and time of the date joined by the classmate.', verbose_name='Date Joined')),
                ('gender', models.ForeignKey(blank=True, help_text='Designates the foreign field of the Gender model.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleague.gender', verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'Classmate',
                'verbose_name_plural': 'Classmates',
            },
        ),
    ]
